# Generated by Django 3.2.6 on 2021-08-10 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_employee_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='emp',
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_key', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('expiry_date', models.DateField()),
                ('dl_type', models.CharField(max_length=20)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.employee')),
            ],
            options={
                'db_table': 'license',
            },
        ),
    ]
